
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Download, FileText, Mail, Share2 } from "lucide-react";
import { toast } from "sonner";

interface ExportReportProps {
  analysisData: {
    fileName: string;
    score: number;
    jobRole: string;
    date: string;
    suggestions: string[];
    missingKeywords: string[];
  };
}

export const ExportReport = ({ analysisData }: ExportReportProps) => {
  const generatePDFReport = () => {
    // Simulate PDF generation
    toast.success("PDF report generated! Download started.");
    
    // Create a simple text report for demo
    const reportContent = `
RESUME ATS ANALYSIS REPORT
=========================

File: ${analysisData.fileName}
Analysis Date: ${new Date(analysisData.date).toLocaleDateString()}
Target Role: ${analysisData.jobRole}
ATS Score: ${analysisData.score}/100

MISSING KEYWORDS:
${analysisData.missingKeywords.map(keyword => `• ${keyword}`).join('\n')}

IMPROVEMENT SUGGESTIONS:
${analysisData.suggestions.map(suggestion => `• ${suggestion}`).join('\n')}

Generated by Resume ATS Analyzer
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ATS_Report_${analysisData.fileName.replace(/\.[^/.]+$/, "")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const emailReport = () => {
    const subject = `ATS Analysis Report - ${analysisData.fileName}`;
    const body = `Hi,\n\nI've analyzed my resume using the ATS Analyzer and got a score of ${analysisData.score}/100 for ${analysisData.jobRole} positions.\n\nKey areas for improvement:\n${analysisData.suggestions.slice(0, 3).map(s => `• ${s}`).join('\n')}\n\nBest regards`;
    
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  const shareResults = () => {
    if (navigator.share) {
      navigator.share({
        title: 'My ATS Resume Score',
        text: `I just analyzed my resume and got an ATS score of ${analysisData.score}/100! Check out this Resume ATS Analyzer.`,
        url: window.location.href,
      });
    } else {
      navigator.clipboard.writeText(`I just analyzed my resume and got an ATS score of ${analysisData.score}/100! Check out this Resume ATS Analyzer: ${window.location.href}`);
      toast.success("Share text copied to clipboard!");
    }
  };

  return (
    <Card className="bg-gray-900/50 backdrop-blur-xl border border-gray-800 shadow-2xl">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Download className="h-5 w-5 text-purple-400" />
          Export & Share
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          <Button
            onClick={generatePDFReport}
            variant="outline"
            className="flex items-center gap-2 border-gray-700 hover:bg-gray-800"
          >
            <FileText className="h-4 w-4" />
            Download PDF
          </Button>
          
          <Button
            onClick={emailReport}
            variant="outline"
            className="flex items-center gap-2 border-gray-700 hover:bg-gray-800"
          >
            <Mail className="h-4 w-4" />
            Email Report
          </Button>
          
          <Button
            onClick={shareResults}
            variant="outline"
            className="flex items-center gap-2 border-gray-700 hover:bg-gray-800"
          >
            <Share2 className="h-4 w-4" />
            Share Results
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};
